ARG WP_VERSION
FROM wordpress:${WP_VERSION}-php8.0
ARG WP_CONFIG_IMPORT_PATH
ARG HOST_USER
# 1. Hook into wp-config.php to add custom configs
# 2. Enable Thumbnail generation for PDFs
# 3. Add the same user that creates the container into it
#    so as there were no ownership conflicts around wp-content folder.
RUN sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>//' /etc/ImageMagick-6/policy.xml &&\
  useradd $HOST_USER || echo "User $HOST_USER already exists."

USER ${HOST_USER}:${HOST_USER}
