ARG WP_VERSION
ARG PHP_VERSION

FROM wordpress:${WP_VERSION}-php${PHP_VERSION}
# Enable Thumbnail generation for PDFs
RUN \
  sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>//' /etc/ImageMagick-*/policy.xml &&\
  useradd wp-user
USER wp-user
